### ISSUE TITLE
TaskAliasDeclaration invoked inside TaskAliasDeclaration ends with a context exception

### ISSUE THREAD

**Issue by blackandred** [riotkit-org/riotkit-do#43]
```bash
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.6/bin/rkd", line 8, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/rkd/__init__.py", line 78, in main
    app.main(argv=sys.argv)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/rkd/__init__.py", line 55, in main
    resolver.resolve(requested_tasks, TaskDeclarationValidator.assert_declaration_is_valid)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/rkd/resolver.py", line 44, in resolve
    self._resolve_element(task_request, callback, task_num)
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/rkd/resolver.py", line 92, in _resolve_element
    declaration.get_args() + task_request.args()
AttributeError: 'GroupDeclaration' object has no attribute 'get_args'
The command "rkd :release:pypi" exited with 1.
```

**Analysis:** The TaskAliasDeclaration is not recursively resolved

**Comment by blackandred** [comment]
Fixed.
